# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  layoutBackgroundHeaderSpace = false
  layoutBackgroundBlur = false # only used when layout equals background
  homepageImage = "img/sakura.gif" # used in: hero, and card
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = true
  showSummary = true
  showZenMode = true
  # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]

[list]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  # apiKey = "AIzaSyA-cHCq8fFEp_bIRQGQKiZ8o5ajN0hqEqU"
  # authDomain = "adilhyz.firebaseapp.com"
  # projectId = "adilhyz"
  # storageBucket = "adilhyz.appspot.com"
  # messagingSenderId = "1063051753951"
  # appId = "1:1063051753951:web:a2cc66f09e10a57cfaac6a"
  # measurementId = "G-71Y5ZP8TEG"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  google = "NHvHI9eXPgvDfd-O1_SPm7KOni4LulB0I0SBjiX_gtg"
  bing = "CD8D07AFE0E46B67F42B15CA56D28FDE"
  pinterest = "8bae5246d2483c34b2ffac84a49d27a9"
  yandex = "c7951f282de9f65b"

[umamiAnalytics]
  websiteid = "40753570-2c69-4a05-8fb7-13f0b8163a58"
  # domain = "adilhyz.github.io"